Made migrator more tollerant of an absent database

diff --git a/files/usr/bin/application-migrate b/files/usr/bin/application-migrate
--- a/files/usr/bin/application-migrate
+++ b/files/usr/bin/application-migrate
@@ -6,20 +6,39 @@ echo "Application Migrate"
 # $ docker run ubuntu-16-laravel-application application-migrate
 #
 
-php artisan --no-ansi --no-interaction migrate:status
+# Get the initial status so that it can be logged
+# - Retry a few times in case we started before the database container
+LIMIT=10
+false
+while [[ $? -ne 0 ]]; do
+	LIMIT=$[$LIMIT-1]
+	if [[ $LIMIT -le 0 ]]; then
+		echo "Unable to get migration status after several attempts - giving up (is the database ok?)"
+		exit 5
+	fi
+	php artisan --no-ansi --no-interaction migrate:status
+done
+
+# Fail on any error after this point
+set -o errexit
+
 echo ""
 echo ""
 
+# Do the migration
 php artisan --no-ansi --no-interaction migrate --force
 echo ""
 echo ""
 
+# Clear the cache
 php artisan --no-ansi --no-interaction cache:clear
 echo ""
 echo ""
 
+# Report the new status
 php artisan --no-ansi --no-interaction migrate:status
 echo ""
 echo ""
 
+# Wait to be told that we need to start again
 exec /init/supervisord
