Added stop on error directive to all shell scripts

diff --git a/files/usr/bin/application-all b/files/usr/bin/application-all
--- a/files/usr/bin/application-all
+++ b/files/usr/bin/application-all
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Stop on error
+set -e
+
 echo "Application All In One"
 #
 # To run everything in a single container you don't need to specify anything
diff --git a/files/usr/bin/application-component-disable b/files/usr/bin/application-component-disable
--- a/files/usr/bin/application-component-disable
+++ b/files/usr/bin/application-component-disable
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Stop on error
+set -e
+
 COMPONENT=$1
 
 if [[ -z "$COMPONENT" ]]; then
diff --git a/files/usr/bin/application-migrator b/files/usr/bin/application-migrator
--- a/files/usr/bin/application-migrator
+++ b/files/usr/bin/application-migrator
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Stop on error
+set -e
+
 echo "Application Migrator"
 #
 # To run just the application migrator in its own container use
diff --git a/files/usr/bin/application-scheduler b/files/usr/bin/application-scheduler
--- a/files/usr/bin/application-scheduler
+++ b/files/usr/bin/application-scheduler
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Stop on error
+set -e
+
 echo "Application Scheduler"
 #
 # To run just the application scheduler in its own container use
diff --git a/files/usr/bin/application-web b/files/usr/bin/application-web
--- a/files/usr/bin/application-web
+++ b/files/usr/bin/application-web
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Stop on error
+set -e
+
 echo "Application Web Interface"
 #
 # To run just the application web interface in its own container use
diff --git a/files/usr/bin/application-worker b/files/usr/bin/application-worker
--- a/files/usr/bin/application-worker
+++ b/files/usr/bin/application-worker
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Stop on error
+set -e
+
 echo "Application Worker"
 #
 # To run just the application worker in its own container use
